### ISSUE TITLE
Swap `operator<<` and `operator>>` to be similar to C++ streams

### ISSUE THREAD

**Issue by longnguyen2004** [andreiavrammsd/cpp-channel#27]
Currently, the channel is on the right side of the operator, which is backwards from the C++ streams syntax, and makes chaining impossible (or at least very annoying) because `<<` and `>>` are left associative. I suggest swapping the 2 operators in order to match C++ streams syntax.

**Comment by andreiavrammsd** [comment]
Sounds like a good point. Thanks for the idea! I will consider this. Let's leave the issue open until I get the time for this.

**Comment by andreiavrammsd** [comment]
@longnguyen2004, please take a look at #28 or directly see the [new documentation](https://github.com/andreiavrammsd/cpp-channel/tree/stream-order#usage).
