### ISSUE TITLE
Does not support `msd::channel<std::function<void()>>`

### ISSUE THREAD

**Issue by leiless** [andreiavrammsd/cpp-channel#29]
It seems that `msd::channel` does not support function pointer.

```c++
[]() {} >> chan;
( []() {} ) >> chan;
```

**Comment by andreiavrammsd** [comment]
I never considered this. Is there a real use case to pass functions between threads?

**Comment by leiless** [comment]
I have a single socket fd, in which all the messages (request and response) should be done sequentially.
So I want some callback to be passed to sequentia-lize betweens those messages.

**Comment by andreiavrammsd** [comment]
Understood. It will take me a while to find time for this. Please leave the issue open.

If it's urgent for you, I can only suggest to use a class in the channel (with dynamic polymorphism or std::variant) if it's suitable for you.

**Comment by andreiavrammsd** [comment]
This is because you try to push a lambda into a channel with type `std::function<void()>`. But the lambda does not have that type; it has a [unique type](https://eel.is/c++draft/expr.prim.lambda#closure).

You can assign a lambda to a std::function object.

```cpp
using function_type = std::function<void()>;
msd::channel<function_type> channel;

const function_type func = []() {};
channel << func;

function_type out;
channel >> out;
out();
```

Does this help you?

**Comment by andreiavrammsd** [comment]
@leiless, have you tested this?

**Comment by andreiavrammsd** [comment]
When you test again, please come back if the proposed solution does not work.
