### ISSUE TITLE
to compile example streaming.cpp error under vs2022

### ISSUE THREAD

**Issue by zack-luan** [andreiavrammsd/cpp-channel#33]
The following code encountered an error while compiling **streaming.cpp** under VS2022：

template <typename T>
struct std::iterator_traits<msd::blocking_iterator<T>> {
    using value_type = typename msd::blocking_iterator<T>::value_type;
    using iterator_category = std::output_iterator_tag;
};

The error message is as follows:
C2794 “reference”:  not “std::iterator_traits<_Iter>” ....

following improvements be made?

template <typename T>
struct std::iterator_traits<Yuanling::ThreadSafeChannelIterator<T>> {
    using value_type = typename Yuanling::ThreadSafeChannelIterator<T>::ValueType;
    using iterator_category = std::output_iterator_tag;
    using reference = std::reference_wrapper<T>;
};

**Comment by andreiavrammsd** [comment]
I'll get to this. Thank you!
