### ISSUE TITLE
Iterator only usable with default constructible class

### ISSUE THREAD

**Issue by schaumb** [andreiavrammsd/cpp-channel#36]
[This line](https://github.com/andreiavrammsd/cpp-channel/blob/master/include/msd/blocking_iterator.hpp#L37C28-L37C28) will fail if the type of the class is not default constructible.

It is a limitation which not mentioned in the readme.

**Comment by andreiavrammsd** [comment]
Thanks! I added it to the [readme](https://github.com/andreiavrammsd/cpp-channel#channel).
