### ISSUE TITLE
Question about possible future target

### ISSUE THREAD

**Issue by RubenRBS** [andreiavrammsd/cpp-channel#39]
Hi, I'm looking into adding this library into Conan Center index,
and a few questions came up during the review process of https://github.com/conan-io/conan-center-index/pull/23136

My main question is if you expect to ever use targets, and if so, what do you expect it to be.

/cc @toge

**Comment by andreiavrammsd** [comment]
Hi. At the moment, I don't see a use case for any other type of target except interface library. I don't plan to offer precompiled objects.

**Comment by andreiavrammsd** [comment]
@RubenRBS, did it help?

**Comment by RubenRBS** [comment]
Oh my, sorry about that, I thought I had replied!

Yes, we have now merged the PR thanks to your clarifications :) Thanks a lot!
