### ISSUE TITLE
Hope

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [andreiavrammsd/cpp-channel#7]
I like the idea, and the execution. This would make transferring data between threads so much easier. I hope this gets added into C++23 (C++20 is finalized).

**Comment by andreiavrammsd** [comment]
Thanks for the appreciation!

There are various methods of dealing with data that moves through threads. My implementation is based on a mutex variable, which could be not suited for all cases when performance is really important. And there are also other aspects that would need improvements for the zero-overhead principle aimed in C++.

On the other hand, maybe this library could be indeed useful for many projects. And it would be very sane for it to be tested under various scenarios. If you consider it helpful, please use it and come back with feedback. There is room for improvement. And share it with other people.

**Comment by andreiavrammsd** [comment]
I will close this issue. If you or someone you know will use this library and have feedback, I'm waiting for it.

Thanks again!
